package com.construccionia.app.data.local

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.filters.SmallTest
import com.construccionia.app.data.models.Infographic
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Test de integración para [InfographicDao] usando Room en memoria.
 *
 * Estos tests requieren un emulador o dispositivo Android (no son unit tests puros).
 * Se ejecutan con AndroidJUnit4.
 */
@RunWith(AndroidJUnit4::class)
@SmallTest
class InfographicDaoTest {

    private lateinit var database: AppDatabase
    private lateinit var dao: InfographicDao

    private val sampleInfographic = Infographic(
        name = "cimientos",
        uriString = "content://test/1",
        filePath = "/storage/downloads/ConstruccionIA/cimientos.png",
        isDemo = false,
        createdAt = 1000L,
        version = 1
    )

    @Before
    fun setup() {
        val context = ApplicationProvider.getApplicationContext<Context>()
        database = Room.inMemoryDatabaseBuilder(
            context,
            AppDatabase::class.java
        ).allowMainThreadQueries().build()
        dao = database.infographicDao()
    }

    @After
    fun tearDown() {
        database.close()
    }

    // ── Insertar y leer ──

    @Test
    fun `insert and read infographic by id`() = runBlocking {
        val id = dao.insert(sampleInfographic)
        assertTrue("ID should be > 0", id > 0)

        val loaded = dao.getById(id)
        assertNotNull("Should find infographic by id", loaded)
        assertEquals("cimientos", loaded?.name)
        assertEquals("/storage/downloads/ConstruccionIA/cimientos.png", loaded?.filePath)
    }

    @Test
    fun `insert and read infographic by file name`() = runBlocking {
        dao.insert(sampleInfographic)

        val loaded = dao.getByFileName("/storage/downloads/ConstruccionIA/cimientos.png")
        assertNotNull("Should find infographic by file path", loaded)
        assertEquals("cimientos", loaded?.name)
    }

    @Test
    fun `insert multiple infographics and verify count`() = runBlocking {
        val infographic2 = sampleInfographic.copy(
            name = "estructura",
            filePath = "/storage/downloads/ConstruccionIA/estructura.png"
        )
        val infographic3 = sampleInfographic.copy(
            name = "instalaciones",
            filePath = "/storage/downloads/ConstruccionIA/instalaciones.png"
        )

        dao.insertAll(listOf(sampleInfographic, infographic2, infographic3))

        val count = dao.count().first()
        assertEquals(3, count)
    }

    @Test
    fun `insert with autoGenerated id auto increments`() = runBlocking {
        val id1 = dao.insert(sampleInfographic)
        val id2 = dao.insert(
            sampleInfographic.copy(
                name = "segundo",
                filePath = "/storage/downloads/ConstruccionIA/segundo.png"
            )
        )
        val id3 = dao.insert(
            sampleInfographic.copy(
                name = "tercero",
                filePath = "/storage/downloads/ConstruccionIA/tercero.png"
            )
        )

        assertTrue("id2 > id1", id2 > id1)
        assertTrue("id3 > id2", id3 > id2)
    }

    // ── Buscar por nombre ──

    @Test
    fun `searchByName returns matching infographics`() = runBlocking {
        dao.insert(sampleInfographic)
        dao.insert(
            sampleInfographic.copy(
                name = "cimientos-reforzados",
                filePath = "/storage/downloads/ConstruccionIA/cimientos-reforzados.png"
            )
        )
        dao.insert(
            sampleInfographic.copy(
                name = "estructura-metalica",
                filePath = "/storage/downloads/ConstruccionIA/estructura.png"
            )
        )

        val results = dao.searchByName("cimiento").first()
        assertEquals(2, results.size)
        assertTrue(results.any { it.name == "cimientos" })
        assertTrue(results.any { it.name == "cimientos-reforzados" })
    }

    @Test
    fun `searchByName returns empty for non matching query`() = runBlocking {
        dao.insert(sampleInfographic)

        val results = dao.searchByName("noexiste").first()
        assertTrue(results.isEmpty())
    }

    @Test
    fun `searchByName is case insensitive`() = runBlocking {
        dao.insert(sampleInfographic.copy(name = "CIMIENTOS"))

        val results = dao.searchByName("cimientos").first()
        assertEquals(1, results.size)
    }

    @Test
    fun `searchByName with empty query returns all`() = runBlocking {
        dao.insert(sampleInfographic)
        dao.insert(
            sampleInfographic.copy(
                name = "otro",
                filePath = "/otro.png"
            )
        )

        // LIKE '%%' coincide con todo
        val results = dao.searchByName("").first()
        assertEquals(2, results.size)
    }

    // ── getAllInfographics flow ──

    @Test
    fun `getAllInfographics flow emits inserted data ordered by createdAt desc`() = runBlocking {
        val infographicOld = sampleInfographic.copy(
            name = "old",
            createdAt = 500L,
            filePath = "/old.png"
        )
        val infographicNew = sampleInfographic.copy(
            name = "new",
            createdAt = 2000L,
            filePath = "/new.png"
        )

        dao.insert(infographicOld)
        dao.insert(infographicNew)

        val allInfographics = dao.getAllInfographics().first()
        assertEquals(2, allInfographics.size)
        // Debe estar ordenado por created_at DESC
        assertEquals("new", allInfographics[0].name)
        assertEquals("old", allInfographics[1].name)
    }

    @Test
    fun `getAllInfographics flow emits empty list when no data`() = runBlocking {
        val allInfographics = dao.getAllInfographics().first()
        assertTrue(allInfographics.isEmpty())
    }

    @Test
    fun `getAllInfographics flow updates after insert`() = runBlocking {
        var allInfographics = dao.getAllInfographics().first()
        assertTrue(allInfographics.isEmpty())

        dao.insert(sampleInfographic)

        allInfographics = dao.getAllInfographics().first()
        assertEquals(1, allInfographics.size)
    }

    // ── Actualizar ──

    @Test
    fun `update infographic changes its fields`() = runBlocking {
        val id = dao.insert(sampleInfographic)

        val updated = sampleInfographic.copy(
            id = id,
            name = "cimientos-actualizados",
            version = 2
        )
        dao.update(updated)

        val loaded = dao.getById(id)
        assertNotNull(loaded)
        assertEquals("cimientos-actualizados", loaded?.name)
        assertEquals(2, loaded?.version)
    }

    @Test
    fun `update infographic preserves unchanged fields`() = runBlocking {
        val id = dao.insert(sampleInfographic)

        dao.update(sampleInfographic.copy(id = id, name = "renombrado"))

        val loaded = dao.getById(id)
        assertEquals("renombrado", loaded?.name)
        assertEquals("/storage/downloads/ConstruccionIA/cimientos.png", loaded?.filePath)
        assertEquals(1000L, loaded?.createdAt)
    }

    // ── Eliminar ──

    @Test
    fun `delete infographic by object`() = runBlocking {
        val id = dao.insert(sampleInfographic)
        assertEquals(1, dao.count().first())

        dao.delete(sampleInfographic.copy(id = id))

        assertEquals(0, dao.count().first())
        assertNull(dao.getById(id))
    }

    @Test
    fun `delete infographic by id`() = runBlocking {
        val id = dao.insert(sampleInfographic)
        assertEquals(1, dao.count().first())

        dao.deleteById(id)

        assertEquals(0, dao.count().first())
    }

    @Test
    fun `delete infographic by file path`() = runBlocking {
        dao.insert(sampleInfographic)
        assertEquals(1, dao.count().first())

        dao.deleteByPath("/storage/downloads/ConstruccionIA/cimientos.png")

        assertEquals(0, dao.count().first())
    }

    @Test
    fun `delete non existing infographic does nothing`() = runBlocking {
        dao.insert(sampleInfographic)

        dao.deleteById(999L) // ID que no existe

        assertEquals(1, dao.count().first())
    }

    @Test
    fun `deleteAll removes all infographics`() = runBlocking {
        dao.insert(sampleInfographic)
        dao.insert(
            sampleInfographic.copy(
                name = "otro",
                filePath = "/otro.png"
            )
        )
        assertEquals(2, dao.count().first())

        dao.deleteAll()

        assertEquals(0, dao.count().first())
    }

    // ── OnConflictStrategy REPLACE ──

    @Test
    fun `insert with same filePath replaces existing`() = runBlocking {
        val id1 = dao.insert(sampleInfographic)

        // Insertar otro con mismo filePath pero distinto nombre
        val id2 = dao.insert(
            sampleInfographic.copy(name = "reemplazado")
        )

        // Con REPLACE, debería reemplazar el registro existente
        // El ID puede ser el mismo o nuevo dependiendo de autoGenerate
        val loaded = dao.getByFileName(sampleInfographic.filePath)
        assertNotNull(loaded)
        assertEquals("reemplazado", loaded?.name)
    }

    // ── getById ──

    @Test
    fun `getById returns null for non existing id`() = runBlocking {
        val result = dao.getById(999L)
        assertNull(result)
    }

    // ── count flow ──

    @Test
    fun `count flow tracks insertions and deletions`() = runBlocking {
        assertEquals(0, dao.count().first())

        dao.insert(sampleInfographic)
        assertEquals(1, dao.count().first())

        val id = dao.getByFileName(sampleInfographic.filePath)!!.id
        dao.deleteById(id)
        assertEquals(0, dao.count().first())
    }
}
